### ISSUE TITLE
[Todo] Move solutions

### ISSUE THREAD

**Issue by larrasu** [larrasu/frontend-mentor#1]
### Description
Move solutions to this repo.

### Tasks
- [ ] [fm-multi-step-form](https://github.com/larrasu/fm-multi-step-form)
- [ ] [fm-product-preview-card-component](https://github.com/larrasu/fm-product-preview-card-component)
- [ ] [fm-sunnyside-agency-landing-page](https://github.com/larrasu/fm-sunnyside-agency-landing-page)
- [ ] [fm-ecommerce-product-page](https://github.com/larrasu/fm-ecommerce-product-page)
- [ ] [fm-qr-code-component](https://github.com/larrasu/fm-qr-code-component)
- [ ] [fm-nft-preview-card-component](https://github.com/larrasu/fm-nft-preview-card-component)
- [ ] [fm-rest-countries](https://github.com/larrasu/fm-rest-countries)
