### ISSUE TITLE
 [Todo] Feedback detail page

### ISSUE THREAD

**Issue by larrasu** [larrasu/frontend-mentor#10]
### Description
Complete the feedback detail page.

### Tasks
- [ ] Show request card component
- [ ] Display comments and replies
- [ ] Upvote request
- [ ] Comment on the request
- [ ] Reply to a comment
- [ ] Show edit button if the current user created the request
