### ISSUE TITLE
[Todo] Create feedback page

### ISSUE THREAD

**Issue by larrasu** [larrasu/frontend-mentor#11]
### Description
Complete the create feedback page.

### Tasks
- [ ] Populate select input with categories
- [ ] Save the feedback/request
- [ ] Cancel and go back to the index page
