### ISSUE TITLE
[Todo] Dark mode

### ISSUE THREAD

**Issue by larrasu** [larrasu/frontend-mentor#26]
### :page_facing_up: Description
Complete dark mode for all pages.

### :pushpin: Tasks
- [ ] Index page dark mode
- [ ] Edit page dark mode
- [ ] Create page dark mode
- [ ] View invoice dark mode
